prebuilt_cxx_library(
  name = 'catch', 
  header_namespace = '', 
  header_only = True, 
  exported_headers = [
    'catch.hpp', 
  ], 
  visibility = [
    'PUBLIC', 
  ], 
)

cxx_binary(
  name = 'unit', 
  srcs = glob([
    'test.cpp', 
    'unit/**/*.cpp', 
  ]), 
  deps = [
    '//:wagyu', 
    ':catch', 
  ], 
)
